add labels on unsafe accessors functions to get clearer error messages
Ignore-this: 35d0f067edc69d9ed44bd5d50b3a29ec

Philippe Strauss reported that the error message provoked by a call to
Sql.default was rather obscure:

> Error: This expression has type (< id : 'a; .. > -> 'a) Sql.unsafe
>       but an expression was expected of type
>         (<  > -> < nul : 'b; t : 'c; .. > Sql.t) Sql.unsafe
>       The second object type has no method id

By using labels on those unsafe functions, we can get (slightly)
clearer error messages:

> Error: This expression has type
>          (default_fields:< id : 'a; .. > -> 'a) Sql.unsafe
>        but an expression was expected of type
>          (default_fields:<  > -> < nul : 'b; t : 'c; .. > Sql.t) Sql.unsafe
>        The second object type has no method id

Note the comment in sql.mli on which API calls should get this
labeling layer: it makes no sense to label arguments that only
propagate information (unify types between one of the argument and the
return value), only the calls that unify argument types -- and thus
may raise errors -- should be labeled.

darcs-hash:20120221210939-47e18-f9e14d04392e27c81c8f4075525f0d01daf33108