simultaneous table bindings
Ignore-this: 8e9abd3215934845337c0e58913a98a5

Change in the comprehension semantic to mirror the SQL output (sic) :
in the comprehension part, table are not allowed to depend on each other :

Example :
  << t2 | t in $table:Base.recette$; t2 in $one:t$ >>
Such code was allowed by pa_comp, but translated to invalid SQL :
  (SELECT t2.id AS id, t2.nom AS nom FROM recette AS t, (SELECT t.id AS id, t.nom AS nom) AS t2)
  ERROR: 42P10: subquery in FROM cannot refer to other relations of same query level

There are two fix possibilities :
  - change the input semantic to disallow such table dependencies
  - change the output SQL to do nested selections

I chose the first (for now) because it's the simplest.
User can still explicitely write table dependencies, using nested comprehensions.

darcs-hash:20090822121853-47e18-523f765f832ae87337ca1cfd022ce736e86848a8